
package com.consumer.busbooking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Booking", targetNamespace = "http://endpoint.busbooking.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Booking {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.consumer.busbooking.TicketInfo
     */
    @WebMethod(operationName = "BusBooking")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusBooking", targetNamespace = "http://endpoint.busbooking.com/", className = "com.consumer.busbooking.BusBooking")
    @ResponseWrapper(localName = "BusBookingResponse", targetNamespace = "http://endpoint.busbooking.com/", className = "com.consumer.busbooking.BusBookingResponse")
    @Action(input = "http://endpoint.busbooking.com/Booking/BusBookingRequest", output = "http://endpoint.busbooking.com/Booking/BusBookingResponse")
    public TicketInfo busBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        JourneyInfo arg0);

}
