
package com.consumer.busbooking;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BusBookingImplService", targetNamespace = "http://endpoint.busbooking.com/", wsdlLocation = "http://localhost:8025/BusBookingProviderAppByUsingContractFirstApproach/BusBooking?wsdl")
@HandlerChain(file = "handler-chain.xml")
public class BusBookingImplService
    extends Service
{

    private final static URL BUSBOOKINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSBOOKINGIMPLSERVICE_EXCEPTION;
    private final static QName BUSBOOKINGIMPLSERVICE_QNAME = new QName("http://endpoint.busbooking.com/", "BusBookingImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8025/BusBookingProviderAppByUsingContractFirstApproach/BusBooking?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSBOOKINGIMPLSERVICE_WSDL_LOCATION = url;
        BUSBOOKINGIMPLSERVICE_EXCEPTION = e;
    }

    public BusBookingImplService() {
        super(__getWsdlLocation(), BUSBOOKINGIMPLSERVICE_QNAME);
    }

    public BusBookingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSBOOKINGIMPLSERVICE_QNAME, features);
    }

    public BusBookingImplService(URL wsdlLocation) {
        super(wsdlLocation, BUSBOOKINGIMPLSERVICE_QNAME);
    }

    public BusBookingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSBOOKINGIMPLSERVICE_QNAME, features);
    }

    public BusBookingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusBookingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Booking
     */
    @WebEndpoint(name = "BusBookingImplPort")
    public Booking getBusBookingImplPort() {
        return super.getPort(new QName("http://endpoint.busbooking.com/", "BusBookingImplPort"), Booking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Booking
     */
    @WebEndpoint(name = "BusBookingImplPort")
    public Booking getBusBookingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.busbooking.com/", "BusBookingImplPort"), Booking.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSBOOKINGIMPLSERVICE_EXCEPTION!= null) {
            throw BUSBOOKINGIMPLSERVICE_EXCEPTION;
        }
        return BUSBOOKINGIMPLSERVICE_WSDL_LOCATION;
    }

}
